# X-ray
updateNumericInput(session, "radio_xray_head", value = df$radio_xray_head)
updateNumericInput(session, "radio_xray_neck", value = df$radio_xray_neck)
updateNumericInput(session, "radio_xray_chest", value = df$radio_xray_chest)
updateNumericInput(session, "radio_xray_abd", value = df$radio_xray_abd)
updateNumericInput(session, "radio_xray_spine", value = df$radio_xray_spine)
updateNumericInput(session, "radio_xray_pelvi_sobs", value = df$radio_xray_pelvisobs)
updateNumericInput(session, "radio_xray_pelvis_uro", value = df$radio_xray_pelvisuro)
updateNumericInput(session, "radio_xray_pelvis_other", value = df$radio_xray_pelvisother)
updateNumericInput(session, "radio_xray_lue", value = df$radio_xray_lue)
updateNumericInput(session, "radio_xray_rue", value = df$radio_xray_rue)
updateNumericInput(session, "radio_xray_lle", value = df$radio_xray_lle)
updateNumericInput(session, "radio_xray_rle", value = df$radio_xray_rle)
updateNumericInput(session, "radio_xray_vascular", value = df$radio_xray_vascular)

# Ultrasound
updateNumericInput(session, "radio_ultra_head", value = df$radio_ultra_head)
updateNumericInput(session, "radio_ultra_neck", value = df$radio_ultra_neck)
updateNumericInput(session, "radio_ultra_chest", value = df$radio_ultra_chest)
updateNumericInput(session, "radio_ultra_abd", value = df$radio_ultra_abd)
updateNumericInput(session, "radio_ultra_spine", value = df$radio_ultra_spine)
updateNumericInput(session, "radio_ultra_pelvis_obs", value = df$radio_ultra_pelvisobs)
updateNumericInput(session, "radio_ultra_pelvis_uro", value = df$radio_ultra_pelvisuro)
updateNumericInput(session, "radio_ultra_pelvis_other", value = df$radio_ultra_pelvisother)
updateNumericInput(session, "radio_ultra_lue", value = df$radio_ultra_lue)
updateNumericInput(session, "radio_ultra_rue", value = df$radio_ultra_rue)
updateNumericInput(session, "radio_ultra_lle", value = df$radio_ultra_lle)
updateNumericInput(session, "radio_ultra_rle", value = df$radio_ultra_rle)
updateNumericInput(session, "radio_ultra_vascular", value = df$radio_ultra_vascular)

# CT Scan
updateNumericInput(session, "radio_ctscan_head", value = df$radio_ctscan_head)
updateNumericInput(session, "radio_ctscan_neck", value = df$radio_ctscan_neck)
updateNumericInput(session, "radio_ctscan_chest", value = df$radio_ctscan_chest)
updateNumericInput(session, "radio_ctscan_abd", value = df$radio_ctscan_abd)
updateNumericInput(session, "radio_ctscan_spine", value = df$radio_ctscan_spine)
updateNumericInput(session, "radio_ctscan_pelvis_obs", value = df$radio_ctscan_pelvisobs)
updateNumericInput(session, "radio_ctscan_pelvis_uro", value = df$radio_ctscan_pelvisuro)
updateNumericInput(session, "radio_ctscan_pelvis_other", value = df$radio_ctscan_pelvisother)
updateNumericInput(session, "radio_ctscan_lue", value = df$radio_ctscan_lue)
updateNumericInput(session, "radio_ctscan_rue", value = df$radio_ctscan_rue)
updateNumericInput(session, "radio_ctscan_lle", value = df$radio_ctscan_lle)
updateNumericInput(session, "radio_ctscan_rle", value = df$radio_ctscan_rle)
updateNumericInput(session, "radio_ctscan_vascular", value = df$radio_ctscan_vascular)

# MRI
updateNumericInput(session, "radio_mri_head", value = df$radio_mri_head)
updateNumericInput(session, "radio_mri_neck", value = df$radio_mri_neck)
updateNumericInput(session, "radio_mri_chest", value = df$radio_mri_chest)
updateNumericInput(session, "radio_mri_abd", value = df$radio_mri_abd)
updateNumericInput(session, "radio_mri_spine", value = df$radio_mri_spine)
updateNumericInput(session, "radio_mri_pelvis_obs", value = df$radio_mri_pelvis_obs)
updateNumericInput(session, "radio_mri_pelvis_uro", value = df$radio_mri_pelvis_uro)
updateNumericInput(session, "radio_mri_pelvis_other", value = df$radio_mri_pelvis_other)
updateNumericInput(session, "radio_mri_lue", value = df$radio_mri_lue)
updateNumericInput(session, "radio_mri_rue", value = df$radio_mri_rue)
updateNumericInput(session, "radio_mri_lle", value = df$radio_mri_lle)
updateNumericInput(session, "radio_mri_rle", value = df$radio_mri_rle)
updateNumericInput(session, "radio_mri_vascular", value = df$radio_mri_vascular)
